service: aws-python-http-api-project-infopersonal
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  informacion:
    handler: handler.info
    events:
      - http:
          path: /info
          method: get
